update

diff --git a/ci-application/tasks/acs-image-build-check.yaml b/ci-application/tasks/acs-image-build-check.yaml
--- a/ci-application/tasks/acs-image-build-check.yaml
+++ b/ci-application/tasks/acs-image-build-check.yaml
@@ -33,6 +33,40 @@ spec:
       mountPath: /workspace
   steps:
 ##------------------------------------------------------------------
+# Check new image is ready
+##------------------------------------------------------------------
+    - name: check-image-status
+      image: quay.io/openshift/origin-cli:latest
+      resources: {}
+      script: |
+        #!/usr/bin/env bash
+
+        set +x
+
+        if [[ "$(params.base_check)" != "true" ]]; then
+          echo "Checking if ImageStream tag $(params.image-short-name):$(params.image-tag) is synchronized..."
+
+          echo "Checking status of image : $(params.image-short-name):$(params.image-tag) in ns $(params.image-build-namespace)"
+          
+          for i in {1..12}; do
+            oc get istag $(params.image-short-name):$(params.image-tag) -n $(params.image-build-namespace)
+            echo $?
+            if oc get istag $(params.image-short-name):$(params.image-tag) -n $(params.image-build-namespace) &>/dev/null; then
+              echo "Success: ImageStream is updated and ready for scanning."
+              break
+            fi
+            echo "Tag not ready yet. Retrying in 10 seconds... ($i/12)"
+            sleep 10
+            if [[ "$i" -eq 12 ]]; then
+              echo "Error: ImageStream sync timed out."
+              exit 1
+            fi
+          done
+        fi
+
+      workingDir: /workspace
+
+##------------------------------------------------------------------
 # Rox image check - check built image
 ##------------------------------------------------------------------
     - name: rox-image-build-check
@@ -53,27 +87,6 @@ spec:
         #!/usr/bin/env bash
 
         set +x
-
-        if [[ "$(params.base_check)" != "true" ]]; then
-          echo "Checking if ImageStream tag $(params.image-short-name):$(params.image-tag) is synchronized..."
-
-          echo "Checking status of image : $(params.image-short-name):$(params.image-tag) in ns $(params.image-build-namespace)"
-          
-          for i in {1..12}; do
-            oc get istag $(params.image-short-name):$(params.image-tag) -n $(params.image-build-namespace)
-            echo $?
-            if oc get istag $(params.image-short-name):$(params.image-tag) -n $(params.image-build-namespace) &>/dev/null; then
-              echo "Success: ImageStream is updated and ready for scanning."
-              break
-            fi
-            echo "Tag not ready yet. Retrying in 5 seconds... ($i/12)"
-            sleep 10
-            if [[ "$i" -eq 12 ]]; then
-              echo "Error: ImageStream sync timed out."
-              exit 1
-            fi
-          done
-        fi
 
         curl -s -k -L -H "Authorization: Bearer $ROX_API_TOKEN" \
           "https://$ROX_CENTRAL_ENDPOINT/api/cli/download/roxctl-linux" \
